### ISSUE TITLE
Enable accounting calculation for all users 

### ISSUE THREAD

**Issue by tomlebl** [nomad-nmr/nomad-server#120]
In admin/accounts, if "Users" switch is on, drop down menu to select group is enabled. Add "--all--" option in the list. If "--al--" option is selected than the backend should return data for all users.

**Comment by tomlebl** [comment]
@hunxjunedo This one could be for you.  If you want to take this one on then let me know. I will assign it to you and provide a DB snapshot that you will need.

**Comment by hunxjunedo** [comment]
Sure I think I can do this.

**Comment by tomlebl** [comment]
@hunxjunedo 
Drop me an e-mail on nomad@st-andrewsc.uk. The current DB dump is too big to be uploaded here. It will also reset the backdoor admin password. So, I will need to give you credentials that you can log in.

**Comment by hunxjunedo** [comment]
if I'm not wrong, this logic is already handled by the backend: When the a groupid isnt sent it traverses thru all the groups and therefore all the active users right ?  
![image](https://github.com/nomad-nmr/nomad-server/assets/89797440/22f75e41-77f6-4f16-bb3a-410195e7cde9)

**Comment by tomlebl** [comment]
This is correct. If groupId is undefined then all experiments are accounted and each row in the table corresponds to individual groups. If groupId is defined then only experiments recorded for selected group are accounted and each row of the table corresponds to individual users that belong to the selected group. 
The new feature  is to add option that would send request with groupId defined "---All---" then you would account all experiments but each row would correspond to a user and thus table would show all users that have acquired an experiment in the given period of time. 
The feature would be useful for a smaller labs that has only handful users and groups. 
I hope that makes sense. If not keep asking.

**Comment by hunxjunedo** [comment]
That makes sense, one more thing: do we need to introduce pagination for now as there may be thousands of users ? Or that can be addressed in a separate PR ?

**Comment by tomlebl** [comment]
I would not use pagination. 
Firstly, --all-- option will likely be used only for systems with small  number of users and if group is defined or calculation is on the group level the table is rather small. 
Secondly, I want to export all results into .csv files and pagination would mess that up. That could be another task. 

There is an important reason why the calculations are done the way they are done. Don't change that!
 Your suggested calculation would be quicker but could be inaccurate/wrong. Users can move from one group to another. So, when you calculate the user could be in a different group than it was in time when the experiment was done. I have been down that way. Long resp time is not a problem.

**Comment by hunxjunedo** [comment]
noted, so I'm going without any pagination, however will have to use a smaller dataset to test, since its taking forever to respond with this dump.

**Comment by tomlebl** [comment]
If you set the dates and calculate only since beginning of July or just the month of June it should be quicker.
