### ISSUE TITLE
Export accounting table as excel/.csv file

### ISSUE THREAD

**Issue by tomlebl** [nomad-nmr/nomad-server#15]
Add button that can export accounting table as an excel or .csv file

**Comment by tomlebl** [comment]
@hunxjunedo would you fancy to have a look on this one?

**Comment by hunxjunedo** [comment]
sure! Updating on this soon.

**Comment by tomlebl** [comment]
Great. The export button should got to AccountingControls.jsx next to "Add Grant" button. It would be active only if there would be any results in the table and it would trigger download of the data in the table/state in .csv file.

**Comment by hunxjunedo** [comment]
@tomlebl I looked into and didn't find any way to export csv in a way that supports sub-columns, as seen in the table. Should we flatten the columns ? Like `Alec Cost 1, Alec Cost 2 ` ? Do you have a solution ?

**Comment by tomlebl** [comment]
@hunxjunedo I am sorry for the late response. I was away for a week on a family holiday in the middle of nowhere and it was really difficult to follow up work related things. 
Flattening up the columns seems to be a good solution. I would suggest 
`Alec  Exp Time Manual, Alec Exp Time Auto , Alec Cost` and repeat analogously for the other instruments.

**Comment by tomlebl** [comment]
Do you know what packages are giving you the troubles?

**Comment by hunxjunedo** [comment]
I just can't install a new package to the frontend, it says NPM read error.

**Comment by tomlebl** [comment]
I have never seen an error like that. It might be a problem with the package itself. What's the name of the package?

**Comment by hunxjunedo** [comment]
![image](https://github.com/user-attachments/assets/13445162-f164-4406-8b46-94f08ef0a21c)
no matter what package I try, its giving the same error. NPM is working fine with my other projects.

**Comment by tomlebl** [comment]
This does not seem to be docker related. I have no idea what is going on. You will have to Google it or ask ChatGPT. 
It could be related to your environment. Check this out 
https://stackoverflow.com/questions/17035399/why-this-error-happend-nodejs-error-write-eio

**Comment by hunxjunedo** [comment]
Hey nothing works, if I run the install command in main directory, it goes well. But in the frontend directory it throws the error. Will try resetting the whole env, and clone it again.

**Comment by hunxjunedo** [comment]
Or what If I don't install, just add the name pkg.json file and push it, it should work fine on your end.

**Comment by tomlebl** [comment]
Did you try to delete package-lock.json and /node_modules and then `npm install` again. 
That usually cleared any npm i issues for me in past.

**Comment by tomlebl** [comment]
No worries. There is no rush. I will be off again in the first week of August as well.
Enjoy your holiday.
