### ISSUE TITLE
Delete users 

### ISSUE THREAD

**Issue by tomlebl** [nomad-nmr/nomad-server#92]
We should enable deleting users if they have not acquired any experiments yet. 
It would be done through checkboxes and action button. On backend we would check if a user has any experiments and if not then delete user and if yes we would make them inactive.

**Comment by tomlebl** [comment]
@hunxjunedo 
You could possibly have a look on this one. It would require to add checkboxes in user table and action button in /NavBar/PageHeader/UsersTabControls that would delete all checked users. You will need to check on backend if there are any experiments that belong to the user that is  going to be deleted. If user has experiments than it does not get deleted but instead it becomes inactive {isActive: false}. Upon receiving response you could display message/modal.info  showing how many users were deleted/made inactive. 
This one is slightly harder than previous two but in the same corner of the app that you have become familiar with.

**Comment by hunxjunedo** [comment]
Assign this to me, let me get into this.

**Comment by hunxjunedo** [comment]
Hey sorry for the delay, have been quite busy lately, coming with a PR today inshallah.

**Comment by tomlebl** [comment]
No rush, I have bee quite busy as well. Cheers.
