### ISSUE TITLE
When users are added to group from .csv file last character of e-mail address is getting deleted

### ISSUE THREAD

**Issue by tomlebl** [nomad-nmr/nomad-server#93]
When users are added to group from .csv file last character of e-mail address is getting deleted

**Comment by hunxjunedo** [comment]
requesting assignment, if open to external contributions.

**Comment by tomlebl** [comment]
@hunxjunedo You are more than welcome to have a look on this one. 
I guess that the problem is at frond-end Groups.jsx container where I introduced some sanitization after .csv is read and converted to an array. When I was reading files with two columns username | email , I was getting emails with a comma at the end. So, I just deleted the last character which appears to be a shortcut solution because some other users report that they are getting e-mails without the last characters. It probably depends on a format of the .csv file that is used as the input. 
If you need some more hints and guidance let me know.

**Comment by hunxjunedo** [comment]
I don't feel the need to setup the whole environment for this particular issue, therefore I'm just isolating the CSVreader function in a seperate env, then once its fixed I'll create a pull request.

**Comment by hunxjunedo** [comment]
I've almost reached out the solution, but I need some test data to ensure this never happens again. It will be really appreciated.

**Comment by tomlebl** [comment]
The first column username has to be defined. The second column email is optional. If email is not defined it gets created from username and suffix defined in environmental variables. You can check addUsers controller in /controllers/admin/groups.js to see what happens on the backend.   
[csv test data.csv](https://github.com/nomad-nmr/nomad-server/files/15457012/csv.test.data.csv)
Here is an example of csv file that works that seems to work in the current version. I have asked the user who reported this bug to send me one that does not seem to work in the current version.

**Comment by tomlebl** [comment]
@hunxjunedo 
It seems to work. Thanks. 
You are more than welcome to help with another one. At the moment, there is nothing as easy as this one. So, you would need to get a bit more involved and set the dev environment. It is all set up in Docker and relatively easy to get going. 
Currently, I don't have any funds to pay developers but could buy you a coffee sometimes.

**Comment by hunxjunedo** [comment]
Appreciate that mate, looking forward to contributing to this repo.

**Comment by tomlebl** [comment]
#91 is related to what you have done but it would require changes in both frontend and backend and you would need to set the project up properly on your machine.
